name=input(" enter the name :")
branch=input(" enter the branch :")
gender=input(" enter the gender:")
college=input(" enter the college :")
age=input(" enter the age :")
print(name)
print(branch)
print(gender)
print(college)
print(int(age))
